import { access, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import type { AppIntentsConfig } from "./config.js";

export interface GeneratedArtifact {
  platform: "ios" | "android" | "types";
  path: string;
}

export interface GenerateAppIntentsOptions {
  cwd?: string;
  check?: boolean;
}

export interface GenerateAppIntentsResult {
  artifacts: GeneratedArtifact[];
  changed: boolean;
  message: string;
}

function collectArtifacts(config: AppIntentsConfig, cwd: string): GeneratedArtifact[] {
  const artifacts: GeneratedArtifact[] = [];

  if (config.ios?.output) {
    artifacts.push({ platform: "ios", path: resolve(cwd, config.ios.output) });
  }

  if (config.android?.shortcutsOutput) {
    artifacts.push({
      platform: "android",
      path: resolve(cwd, config.android.shortcutsOutput),
    });
  }

  if (config.types?.output) {
    artifacts.push({ platform: "types", path: resolve(cwd, config.types.output) });
  }

  return artifacts;
}

function renderArtifact(artifact: GeneratedArtifact): string {
  switch (artifact.platform) {
    case "ios":
      return [
        "// Generated by react-native-app-intents (scaffold placeholder).",
        "import AppIntents",
        "",
        "struct GeneratedAppIntentsPlaceholder {}",
        "",
      ].join("\n");
    case "android":
      return [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<shortcuts>",
        "  <!-- Generated by react-native-app-intents (scaffold placeholder). -->",
        "</shortcuts>",
        "",
      ].join("\n");
    case "types":
      return [
        "// Generated by react-native-app-intents (scaffold placeholder).",
        "export type AppIntentEvent = never;",
        "",
      ].join("\n");
  }
}

export async function generateAppIntents(
  config: AppIntentsConfig,
  options: GenerateAppIntentsOptions = {},
): Promise<GenerateAppIntentsResult> {
  const cwd = options.cwd ?? process.cwd();
  const artifacts = collectArtifacts(config, cwd);

  if (options.check) {
    for (const artifact of artifacts) {
      await access(artifact.path);
    }

    return {
      artifacts,
      changed: false,
      message: artifacts.length === 0 ? "No outputs configured." : "Scaffold outputs are present.",
    };
  }

  for (const artifact of artifacts) {
    await mkdir(dirname(artifact.path), { recursive: true });
    await writeFile(artifact.path, renderArtifact(artifact), "utf8");
  }

  return {
    artifacts,
    changed: artifacts.length > 0,
    message:
      artifacts.length === 0
        ? "No outputs configured."
        : `Wrote ${artifacts.length} scaffold artifact${artifacts.length === 1 ? "" : "s"}.`,
  };
}
